version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:1.5.7
    container_name: chroma_enterprise_server
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=FALSE
    restart: unless-stopped